<a href="https://colab.research.google.com/github/rahul-singh2021/machine_learning/blob/main/credit_card_churn_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data=pd.read_csv("/content/Churn_Modelling[1].csv")

In [3]:
data.head()


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
data.drop(columns =['RowNumber','CustomerId','Surname'],inplace=True)

In [6]:
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [7]:
data['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [8]:
data['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [9]:
data=pd.get_dummies(data,columns=['Geography','Gender'],drop_first=True)

In [10]:
data.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1                  0   
1               1        112542.58       0                  0   
2               0        113931.57       1                  0   
3               0         93826.63       0                  0   
4               1         79084.10       0                  0   

   Geography_Spain  Gender_Male  
0                0            0  
1                1            0  
2                0            0  
3                0            0  
4                1            0

In [11]:
data.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Geography_Germany',
       'Geography_Spain', 'Gender_Male'],
      dtype='object')

In [12]:
x=data.drop(columns=['Exited'])

In [13]:
y=data['Exited']

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
data

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1        101348.88       1                  0   
1                  1        112542.58       0                  0   
2                  0        113931.57       1                  0   
3                  0         93826.63       0                  0   
4                  1         79084.10       0                  0   
...              ...              ...     ...                ...   
9995               0         96270.64       0                  0   
9996               1        101699.77       0                  0   
9997               1         42085.58       1                  0   
9998               0         92888.52       1                  1   
9999               0         38190.78       0                  0   

      Geography_Spain  Gender_Male  
0                   0            0  
1                   1            0  
2                   0            0  
3                   0            0  
4                   1            0  
...               ...          ...  
9995                0            1  
9996                0            1  
9997                0            0  
9998                0            1  
9999                0            0  

[10000 rows x 12 columns]

In [16]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x_train_trf=scaler.fit_transform(x_train)
x_test_trf=scaler.fit_transform(x_test)

In [17]:
x_train_trf

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [18]:
!pip install tensorflow

In [19]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [20]:
model=Sequential()

model.add(Dense(7,activation='sigmoid',input_dim=11))
model.add(Dense(5,activation='sigmoid'))
model.add(Dense(4,activation='sigmoid'))
model.add(Dense(4,activation='sigmoid'))
model.add(Dense(1,activation='sigmoid'))

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 7)                 84        
                                                                 
 dense_1 (Dense)             (None, 5)                 40        
                                                                 
 dense_2 (Dense)             (None, 4)                 24        
                                                                 
 dense_3 (Dense)             (None, 4)                 20        
                                                                 
 dense_4 (Dense)             (None, 1)                 5         
                                                                 
Total params: 173 (692.00 Byte)
Trainable params: 173 (692.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
model.compile(optimizer='Adam',loss='binary_crossentropy')

In [23]:
history=model.fit(x_train,y_train,batch_size=50,epochs=1000)

Epoch 1/1000
160/160 [==============================] - 2s 2ms/step - loss: 0.5728
Epoch 2/1000
160/160 [==============================] - 0s 3ms/step - loss: 0.5174
Epoch 3/1000
160/160 [==============================] - 0s 3ms/step - loss: 0.5071
Epoch 4/1000
160/160 [==============================] - 1s 3ms/step - loss: 0.5059
Epoch 5/1000
160/160 [==============================] - 1s 5ms/step - loss: 0.5059
Epoch 6/1000
160/160 [==============================] - 1s 3ms/step - loss: 0.5059
Epoch 7/1000
160/160 [==============================] - 0s 2ms/step - loss: 0.5058
Epoch 8/1000
160/160 [==============================] - 0s 2ms/step - loss: 0.5058
Epoch 9/1000
160/160 [==============================] - 0s 2ms/step - loss: 0.5057
Epoch 10/1000
160/160 [==============================] - 0s 2ms/step - loss: 0.5056
Epoch 11/1000
160/160 [==============================] - 0s 2ms/step - loss: 0.5055
Epoch 12/1000
160/160 [==============================] - 0s 2ms/step - loss: 0.5054
E

In [24]:
model.layers[1].get_weights()


[array([[ 0.17397058, -0.31421822,  0.5411268 ,  0.4163056 ,  0.22677821],
        [-2.1715672 , -1.8568205 ,  2.2457402 , -2.6378164 , -2.1601524 ],
        [-1.1446697 , -0.02844002,  0.54504615, -0.02622262, -0.682298  ],
        [ 0.68021995,  0.616569  , -0.1027891 ,  0.633282  , -0.42457876],
        [-0.17328581, -0.5211579 ,  0.22606127, -0.027937  , -0.72933453],
        [ 2.4668682 ,  2.8376038 , -3.6080937 ,  2.5435936 ,  2.0030496 ],
        [-0.12864383, -0.56601334,  0.13793987, -0.6820068 ,  0.2336229 ]],
       dtype=float32),
 array([-0.4400102 , -0.5752911 ,  0.85874295, -0.64338446, -0.4953303 ],
       dtype=float32)]

In [25]:
y_pred=model.predict(x_test)

63/63 [==============================] - 0s 2ms/step


In [26]:
y_pred

array([[0.23798971],
       [0.23798971],
       [0.23798971],
       ...,
       [0.23798971],
       [0.22679849],
       [0.23798971]], dtype=float32)

In [27]:
import numpy as np

In [28]:
final_pred=np.where(y_pred>=0.5,1,0)

In [29]:
final_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(final_pred,y_test)

0.7975