<a href="https://colab.research.google.com/github/rahul-singh2021/machine_learning/blob/main/ML_LAB_RANDOM_FOREST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, confusion_matrix

import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/aniruddhachoudhury/Red-wine-Quality/master/winequality-red.csv")
data.columns
data.quality.unique()
data.quality.value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [4]:

X= data.drop(columns=('quality'))

In [5]:
y = data ['quality']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=20)

In [14]:
rf_classifier = RandomForestClassifier(n_estimators = 100, max_depth = None, random_state=20)

In [15]:
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=20)

In [16]:
y_pred = rf_classifier.predict(X_test)

In [17]:
accuracy= accuracy_score(y_test, y_pred)


In [18]:
print("Accuracy:", accuracy)

Accuracy: 0.709375


In [19]:
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
classification_rep = classification_report(y_test, y_pred)

Confusion Matrix:
[[  0   0   1   0   0   0]
 [  0   0   5   2   0   0]
 [  0   0 106  22   2   0]
 [  0   1  35  94   6   0]
 [  0   0   2  15  27   0]
 [  0   0   0   0   2   0]]


In [20]:
print("Classification Report:")
print(classification_rep)

Classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         7
           5       0.71      0.82      0.76       130
           6       0.71      0.69      0.70       136
           7       0.73      0.61      0.67        44
           8       0.00      0.00      0.00         2

    accuracy                           0.71       320
   macro avg       0.36      0.35      0.35       320
weighted avg       0.69      0.71      0.70       320

