<a href="https://colab.research.google.com/github/rahul-singh2021/machine_learning/blob/main/ML_LAB_NAIVE_BAYES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, confusion_matrix

import warnings
warnings.filterwarnings('ignore')

In [4]:
data = pd.read_csv("https://raw.githubusercontent.com/aniruddhachoudhury/Red-wine-Quality/master/winequality-red.csv")
data.columns
data.quality.unique()
data.quality.value_counts()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [48]:
X= data.drop(columns=('quality'))

In [49]:
y = data ['quality']

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.23 random_state=10)

SyntaxError: ignored

In [55]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train,y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(conf_matrix)

classification_rep = classification_report(y_test, y_pred)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.525
Confusion Matrix:
[[ 0  0  1  0  0  0]
 [ 0  0  5  2  0  0]
 [ 1  9 86 29  5  0]
 [ 0  4 46 56 30  0]
 [ 0  1  3 14 26  0]
 [ 0  0  0  0  2  0]]
Classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         7
           5       0.61      0.66      0.63       130
           6       0.55      0.41      0.47       136
           7       0.41      0.59      0.49        44
           8       0.00      0.00      0.00         2

    accuracy                           0.53       320
   macro avg       0.26      0.28      0.27       320
weighted avg       0.54      0.53      0.53       320

