<a href="https://colab.research.google.com/github/rahul-singh2021/machine_learning/blob/main/ML_LAB_28_aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [2]:
data={
    'plot_size': [100,150,200,250,300,350,400,450,500],
    'plot_price': [200000,250000,300000,350000,400000,450000,500000,550000,600000]
}

In [15]:
d=pd.DataFrame(data)

In [16]:
d

plot_size  plot_price
0        100      200000
1        150      250000
2        200      300000
3        250      350000
4        300      400000
5        350      450000
6        400      500000
7        450      550000
8        500      600000

In [17]:
x=d[['plot_size']]
y=d[['plot_price']]

In [18]:
model=LinearRegression()

In [19]:
model.fit(x,y)

LinearRegression()

In [20]:
new_sizes=[[600],[700]]

In [21]:
model.predict([[500]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[600000.]])

In [22]:
model.predict([[700]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[800000.]])

In [23]:
df=pd.read_csv('/content/Salary_Data[1].csv')

In [24]:
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [27]:
X=df[['YearsExperience']]
Y=df[['Salary']]

In [28]:
reg=LinearRegression()

In [29]:
reg.fit(X,Y)

LinearRegression()

In [37]:
reg.predict([[1.1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[36187.15875227]])

In [38]:
reg.score(X,Y)

0.9569566641435086

In [41]:
data={
    'Age': [25,30,35,40,45,50,55,60],
    'Years_of_Experience': [2,5,8,10,12,15,18,20],
    'Salary': [50000,60000,75000, 80000, 90000, 100000, 110000, 120000]
}

In [43]:
file=pd.DataFrame(data)

In [44]:
file

Age  Years_of_Experience  Salary
0   25                    2   50000
1   30                    5   60000
2   35                    8   75000
3   40                   10   80000
4   45                   12   90000
5   50                   15  100000
6   55                   18  110000
7   60                   20  120000

In [50]:
x=file.drop(['Salary'],axis='columns')
y=file[['Salary']]

In [51]:
mod=LinearRegression()

In [52]:
mod.fit(x,y)

LinearRegression()

In [55]:
mod.predict([[45,12]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[88881.57894737]])