<a href="https://colab.research.google.com/github/rahul-singh2021/machine_learning/blob/main/ML_LAB_SVM%26KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,Lasso,RidgeCV,LassoCV,ElasticNet,ElasticNetCV,LogisticRegression
from sklearn.model_selection import train_test_split
#from statsmodels.stats.outliers_influence import varience_inflation_factor
from sklearn.metrics import accuracy_score,confusion_matrix,roc_curve,roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline


sns.set()

In [6]:
df=pd.read_csv('/content/WineQT[1].csv')

In [7]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  ...  sulphates  alcohol  quality  Id
0            7.4              0.70         0.00             1.9  ...       0.56      9.4        5   0
1            7.8              0.88         0.00             2.6  ...       0.68      9.8        5   1
2            7.8              0.76         0.04             2.3  ...       0.65      9.8        5   2
3           11.2              0.28         0.56             1.9  ...       0.58      9.8        6   3
4            7.4              0.70         0.00             1.9  ...       0.56      9.4        5   4

[5 rows x 13 columns]

In [8]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'Id'],
      dtype='object')

In [10]:
df.quality.unique()


array([5, 6, 7, 4, 8, 3])

In [11]:
df.quality.value_counts()

5    483
6    462
7    143
4     33
8     16
3      6
Name: quality, dtype: int64

In [22]:
x=df.drop('quality',axis='columns')
y=df[['quality']]

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler=StandardScaler()

In [27]:
scaler.fit(x_train)

StandardScaler()

In [29]:
print(scaler.mean_)

[8.30087500e+00 5.26243750e-01 2.68950000e-01 2.56343750e+00
 8.59250000e-02 1.57275000e+01 4.64931250e+01 9.96711025e-01
 3.31342500e+00 6.56862500e-01 1.04702083e+01 8.11350000e+02]


In [30]:
x_train_tf=scaler.transform(x_train)
x_train_tf

array([[ 0.56685612, -0.95522003,  0.61909131, ...,  0.46385318,
         0.38767963,  0.0961982 ],
       [ 0.79379715,  0.02158304,  1.69310349, ...,  1.28834013,
         1.74070595, -1.29560555],
       [-0.39764322, -0.95522003,  0.20994381, ..., -0.23378962,
        -0.87514494,  0.7813276 ],
       ...,
       [ 0.28317984,  0.36633706, -0.45492087, ..., -0.7411662 ,
        -0.9653467 , -0.09770635],
       [ 0.3399151 , -1.41489206,  0.92595193, ..., -0.67774413,
         1.65050419,  0.42799042],
       [ 1.07747342, -0.610466  ,  1.53967318, ..., -0.17036754,
        -0.78494319, -1.62739777]])

In [31]:
from sklearn.svm import SVC
model=SVC()

In [32]:
model.fit(x_train_tf,y_train)

SVC()

In [34]:
model.score(x_train_tf,y_train)

0.7

In [35]:
x_test_tf=scaler.transform(x_test)
x_test_tf

array([[-0.1707022 ,  1.02711561, -1.11978556, ...,  1.85913879,
         0.02687261, -1.59938934],
       [-0.45437848,  1.05584511, -1.37550275, ..., -0.48747791,
        -0.42413617,  0.43445391],
       [-0.56784899, -0.09333497, -0.45492087, ...,  0.46385318,
        -0.87514494, -0.13433276],
       ...,
       [-1.02173103,  2.14756618, -1.37550275, ..., -0.17036754,
         0.38767963,  1.38674068],
       [-0.1707022 ,  1.08457461, -0.25034713, ..., -0.7411662 ,
        -0.87514494,  0.99893159],
       [-0.34090797,  0.65363208, -0.30149056, ..., -1.31196485,
        -0.51433792,  1.30917886]])

In [37]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [38]:
y_pred=knn.predict(x_test)

In [39]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix

In [40]:
confusion_matrix(y_test,y_pred)


array([[ 0,  0,  1,  1,  1,  0],
       [ 0,  0,  6,  4,  0,  0],
       [ 0,  3, 90, 34,  8,  0],
       [ 0,  3, 66, 65, 10,  0],
       [ 0,  0, 13, 27,  8,  0],
       [ 0,  0,  1,  2,  0,  0]])