<a href="https://colab.research.google.com/github/rahul-singh2021/machine_learning/blob/main/ML_LAB_DECISION_TREE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')


In [3]:
data=pd.read_csv("https://raw.githubusercontent.com/aniruddhachoudhury/Red-Wine-Quality/master/winequality-red.csv")

In [4]:
data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [5]:
data.quality.unique()

array([5, 6, 7, 4, 8, 3])

In [6]:
data.quality.value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [7]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [8]:
x= data.drop(['quality'],axis='columns')

In [9]:
y = data.quality

In [10]:
x_train,x_test,y_train,y_test= train_test_split(x, y, test_size=0.2, random_state=10)

In [11]:
from sklearn import tree

In [16]:
model = tree.DecisionTreeClassifier()

In [17]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [25]:
print("Model score:",model.score(x_test,y_test))

Model score: 0.621875


In [26]:
y_predict = model.predict(x_test)


In [29]:
 from sklearn.metrics import confusion_matrix, classification_report


In [30]:
cm = confusion_matrix(y_test, y_predict)

In [32]:
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[  0   2   0   0   0   0]
 [  0   2   4   3   0   0]
 [  1   3 102  20   6   0]
 [  0   3  30  75  16   3]
 [  0   2   6  14  20   0]
 [  0   0   0   4   4   0]]


In [36]:
classification_rep=classification_report (y_test, y_predict)

print("Classification Report: ")
print(classification_rep)

Classification Report: 
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.17      0.22      0.19         9
           5       0.72      0.77      0.74       132
           6       0.65      0.59      0.62       127
           7       0.43      0.48      0.45        42
           8       0.00      0.00      0.00         8

    accuracy                           0.62       320
   macro avg       0.33      0.34      0.33       320
weighted avg       0.61      0.62      0.62       320

